import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutShell from "./components/layout/LayoutShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Byte Space",
  description: "Generated by Tushar Sinha",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <LayoutShell>{children}</LayoutShell>

      </body>
    </html>
  );
}
